# Generated by Django 4.0.5 on 2022-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_curator_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='discount_card',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер карты Коммондор'),
        ),
    ]
