# Generated by Django 4.0.5 on 2022-06-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_alter_owner_options_owner_sobes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='curator',
            name='address_reg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес регистрации'),
        ),
        migrations.AddField(
            model_name='curator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='curator',
            name='passport_code',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='curator',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AddField(
            model_name='curator',
            name='passport_issued',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AddField(
            model_name='curator',
            name='passport_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AddField(
            model_name='curator',
            name='tel',
            field=models.CharField(default=9998887766, max_length=10, verbose_name='Телефон без префикса (10 цифр)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='sobes_status',
            field=models.BooleanField(verbose_name='Статус собеседования'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel',
            field=models.CharField(max_length=10, verbose_name='Телефон без префикса (10 цифр)'),
        ),
    ]
