# Generated by Django 4.0.5 on 2022-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_curator_address_reg_curator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон без префикса (10 цифр)'),
        ),
    ]
