# Generated by Django 4.0.5 on 2022-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_alter_curator_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телефон без префикса (10 цифр)'),
        ),
    ]
