# Generated by Django 4.0.5 on 2022-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_alter_owner_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curator',
            name='tel',
            field=models.CharField(default=9853116754, max_length=10, verbose_name='Телефон без префикса (10 цифр)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='tel',
            field=models.CharField(default=8976542331, max_length=10, verbose_name='Телефон без префикса (10 цифр)'),
            preserve_default=False,
        ),
    ]
