# Generated by Django 4.0.5 on 2022-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_alter_curator_tel_alter_owner_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='sobes_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Статус собеседования'),
        ),
    ]
