# Generated by Django 4.0.5 on 2022-06-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_owner_sobes_result_alter_owner_sobes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='dog',
        ),
        migrations.AlterField(
            model_name='dog',
            name='curator',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator', to='dogs.curator', verbose_name='Куратор'),
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_dog', to='dogs.dog', verbose_name='Собака')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_owner', to='dogs.owner', verbose_name='Хозяин')),
            ],
        ),
    ]
