# Generated by Django 4.0.5 on 2022-06-24 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0013_remove_owner_dog_alter_dog_curator_adoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
