# Generated by Django 4.0.5 on 2022-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0014_adoption_add_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'ordering': ['-add_date'], 'verbose_name': 'Пристройство', 'verbose_name_plural': 'Пристройства'},
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='sobes_status',
            new_name='psy_sobes_status',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='sobes_result',
        ),
        migrations.AddField(
            model_name='owner',
            name='first_sobes_result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий куратора'),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_sobes_status',
            field=models.CharField(choices=[('OK', 'Пройдено'), ('DENY', 'Отказ'), ('Not_auditioned', 'Не собеседовался')], default='Not_auditioned', max_length=200, null=True, verbose_name='Статус первичного собеседования'),
        ),
        migrations.AddField(
            model_name='owner',
            name='psy_sobes_result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий зоопсихолога'),
        ),
        migrations.AddConstraint(
            model_name='adoption',
            constraint=models.UniqueConstraint(fields=('owner', 'dog'), name='unique_adoption'),
        ),
    ]
