# Generated by Django 4.0.5 on 2022-06-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0017_owner_had_pets_owner_large_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='contract_signed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Контракт подписан'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='had_pets',
            field=models.BooleanField(blank=True, null=True, verbose_name='Были ли домашние животные'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='sobes_result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
    ]
