# Generated by Django 4.0.5 on 2022-06-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0018_owner_contract_signed_alter_owner_had_pets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Договор подписан'),
        ),
    ]
