# Generated by Django 4.0.5 on 2022-06-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0019_alter_owner_contract_signed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='contract_signed',
        ),
        migrations.AddField(
            model_name='adoption',
            name='contract_signed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Договор подписан'),
        ),
    ]
