# Generated by Django 4.0.5 on 2022-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0020_remove_owner_contract_signed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='had_pets',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='large_place',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='sobes_result',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='sobes_status',
        ),
        migrations.AddField(
            model_name='adoption',
            name='had_pets',
            field=models.BooleanField(blank=True, null=True, verbose_name='Были ли домашние животные'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='large_place',
            field=models.BooleanField(blank=True, null=True, verbose_name='Огромная квартира'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='sobes_result',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='adoption',
            name='sobes_status',
            field=models.CharField(choices=[('OK', 'Пройдено'), ('DENY', 'Отказ'), ('Not_auditioned', 'Не собеседовался')], default='Not_auditioned', max_length=200, null=True, verbose_name='Статус собеседования'),
        ),
    ]
