# Generated by Django 4.0.5 on 2022-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0021_remove_owner_had_pets_remove_owner_large_place_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adoption',
            constraint=models.UniqueConstraint(fields=('contract_signed', 'dog'), name='unique_contract'),
        ),
    ]
