# Generated by Django 4.0.5 on 2022-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0022_adoption_unique_contract'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adoption',
            name='unique_contract',
        ),
        migrations.AddConstraint(
            model_name='adoption',
            constraint=models.UniqueConstraint(fields=('dog', 'contract_signed'), name='unique_contract'),
        ),
    ]
